In [3]:
import pandas as pd

In [4]:
df = pd.read_csv(r'C:\Users\saba\Downloads\weather.csv')
df

,MIN temp (deg Celcius),Location,Time,Wind,MAX temp (deg Celcius),Description,Precipitation (in %),Date,Other Details,Humidity (in %),Day
0,22,"Bharsul, India 10-day Weather",23:04 IST,NE 2 km/h,--,Clear,0,18 OCT,Generally clear. Low 22ºC. Winds NE and variable.,48,Tonight
1,22,"Bharsul, India 10-day Weather",23:04 IST,NNW 7 km/h,36,Mostly Sunny,0,19 OCT,Generally clear. High 36ºC. Winds NNW and vari...,29,Fri
2,22,"Bharsul, India 10-day Weather",23:04 IST,SSW 5 km/h,35,Sunny,0,20 OCT,Generally clear. High 35ºC. Winds SSW and vari...,29,Sat
3,21,"Bharsul, India 10-day Weather",23:04 IST,WSW 9 km/h,36,Sunny,0,21 OCT,Generally clear. High 36ºC. Winds WSW and vari...,32,Sun
4,21,"Bharsul, India 10-day Weather",23:04 IST,N 9 km/h,35,Sunny,0,22 OCT,Generally clear. High 35ºC. Winds N and variable.,31,Mon
5,21,"Bharsul, India 10-day Weather",23:04 IST,W 8 km/h,35,Sunny,0,23 OCT,Generally clear. High 35ºC. Winds W and variable.,29,Tue
6,21,"Bharsul, India 10-day Weather",23:04 IST,SSE 7 km/h,34,Mostly Sunny,0,24 OCT,Generally clear. High 34ºC. Winds SSE and vari...,28,Wed
7,20,"Bharsul, India 10-day Weather",23:04 IST,SSW 9 km/h,34,Mostly Sunny,0,25 OCT,Generally clear. High 34ºC. Winds SSW and vari...,27,Thu
8,20,"Bharsul, India 10-day Weather",23:04 IST,E 7 km/h,34,Mostly Sunny,0,26 OCT,Generally clear. High 34ºC. Winds E and variable.,29,Fri
9,19,"Bharsul, India 10-day Weather",23:04 IST,NE 10 km/h,34,Sunny,0,27 OCT,Generally clear. High 34ºC. Winds NE at 10 to ...,30,Sat
10,19,"Bharsul, India 10-day Weather",23:04 IST,NE 7 km/h,33,Sunny,0,28 OCT,Generally clear. High 33ºC. Winds NE and varia...,28,Sun
11,19,"Bharsul, India 10-day Weather",23:04 IST,ENE 6 km/h,33,Sunny,0,29 OCT,Generally clear. High 33ºC. Winds ENE and vari...,26,Mon
12,19,"Bharsul, India 10-day Weather",23:04 IST,E 6 km/h,33,Sunny,0,30 OCT,Generally clear. High 33ºC. Winds E and variable.,27,Tue
13,19,"Bharsul, India 10-day Weather",23:04 IST,ESE 5 km/h,33,Sunny,0,31 OCT,Generally clear. High 33ºC. Winds ESE and vari...,27,Wed
14,19,"Bharsul, India 10-day Weather",23:04 IST,NNW 5 km/h,33,Sunny,0,1 NOV,Generally clear. High 33ºC. Winds NNW and vari...,28,Thu
15,MIN temp (deg Celcius),Location,Time,Wind,MAX temp (deg Celcius),Description,Precipitation (in %),Date,Other Details,Humidity (in %),Day
16,22,"Bharsul, India 10-day Weather",23:04 IST,NE 2 km/h,--,Clear,0,18 OCT,Generally clear. Low 22ºC. Winds NE and variable.,48,Tonight
17,22,"Bharsul, India 10-day Weather",23:04 IST,NNW 7 km/h,36,Mostly Sunny,0,19 OCT,Generally clear. High 36ºC. Winds NNW and vari...,29,Fri
18,22,"Bharsul, India 10-day Weather",23:04 IST,SSW 5 km/h,35,Sunny,0,20 OCT,Generally clear. High 35ºC. Winds SSW and vari...,29,Sat
19,21,"Bharsul, India 10-day Weather",23:04 IST,WSW 9 km/h,36,Sunny,0,21 OCT,Generally clear. High 36ºC. Winds WSW and vari...,32,Sun
20,21,"Bharsul, India 10-day Weather",23:04 IST,N 9 km/h,35,Sunny,0,22 OCT,Generally clear. High 35ºC. Winds N and variable.,31,Mon
21,21,"Bharsul, India 10-day Weather",23:04 IST,W 8 km/h,35,Sunny,0,23 OCT,Generally clear. High 35ºC. Winds W and variable.,29,Tue
22,21,"Bharsul, India 10-day Weather",23:04 IST,SSE 7 km/h,34,Mostly Sunny,0,24 OCT,Generally clear. High 34ºC. Winds SSE and vari...,28,Wed
23,20,"Bharsul, India 10-day Weather",23:04 IST,SSW 9 km/h,34,Mostly Sunny,0,25 OCT,Generally clear. High 34ºC. Winds SSW and vari...,27,Thu
24,20,"Bharsul, India 10-day Weather",23:04 IST,E 7 km/h,34,Mostly Sunny,0,26 OCT,Generally clear. High 34ºC. Winds E and variable.,29,Fri
25,19,"Bharsul, India 10-day Weather",23:04 IST,NE 10 km/h,34,Sunny,0,27 OCT,Generally clear. High 34ºC. Winds NE at 10 to ...,30,Sat
26,19,"Bharsul, India 10-day Weather",23:04 IST,NE 7 km/h,33,Sunny,0,28 OCT,Generally clear. High 33ºC. Winds NE and varia...,28,Sun
27,19,"Bharsul, India 10-day Weather",23:04 IST,ENE 6 km/h,33,Sunny,0,29 OCT,Generally clear. High 33ºC. Winds ENE and vari...,26,Mon
28,19,"Bharsul, India 10-day Weather",23:04 IST,E 6 km/h,33,Sunny,0,30 OCT,Generally clear. High 33ºC. Winds E and variable.,27,Tue
29,19,"Bharsul, India 10-day Weather",23:04 IST,ESE 5 km/h,33,Sunny,0,31 OCT,Generally clear. High 33ºC. Winds ESE and vari...,27,Wed
30,19,"Bharsul, India 10-day Weather",23:04 IST,NNW 5 km/h,33,Sunny,0,1 NOV,Generally clear. High 33ºC. Winds NNW and vari...,28,Thu

## Basic of Data

In [5]:
print(df.shape)

(31, 11)

In [6]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   MIN temp (deg Celcius)  31 non-null     str
 1   Location                31 non-null     str
 2   Time                    31 non-null     str
 3   Wind                    31 non-null     str
 4   MAX temp (deg Celcius)  31 non-null     str
 5   Description             31 non-null     str
 6   Precipitation (in %)    31 non-null     str
 7   Date                    31 non-null     str
 8   Other Details           31 non-null     str
 9   Humidity (in %)         31 non-null     str
 10  Day                     31 non-null     str
dtypes: str(11)
memory usage: 2.8 KB
None

In [7]:
print(df.describe())

       MIN temp (deg Celcius)                       Location       Time  \
count                      31                             31         31
unique                      5                              2          2
top                        19  Bharsul, India 10-day Weather  23:04 IST
freq                       12                             30         30

              Wind MAX temp (deg Celcius) Description Precipitation (in %)  \
count           31                     31          31                   31
unique          16                      6           4                    2
top     NE 2 km/h                      33       Sunny                    0
freq             2                     10          20                   30

          Date                                      Other Details  \
count       31                                                 31
unique      16                                                 16
top     18 OCT  Generally clear. Low 22ºC. Winds NE and variable.
freq         2                                                  2

       Humidity (in %)  Day
count               31   31
unique               9    9
top                 29  Fri
freq                 8    4

## Total columns

In [8]:
df.columns

Index(['MIN temp (deg Celcius)', 'Location', 'Time', 'Wind',
       'MAX temp (deg Celcius)', 'Description', 'Precipitation (in %)', 'Date',
       'Other Details', 'Humidity (in %)', 'Day'],
      dtype='str')

## maximum rows

In [9]:
print(pd.options.display.max_rows)

60

## index

In [10]:
df.index

RangeIndex(start=0, stop=31, step=1)

## Column Selection

In [11]:
print(df["Time"]) # Single column

0     23:04 IST
1     23:04 IST
2     23:04 IST
3     23:04 IST
4     23:04 IST
5     23:04 IST
6     23:04 IST
7     23:04 IST
8     23:04 IST
9     23:04 IST
10    23:04 IST
11    23:04 IST
12    23:04 IST
13    23:04 IST
14    23:04 IST
15         Time
16    23:04 IST
17    23:04 IST
18    23:04 IST
19    23:04 IST
20    23:04 IST
21    23:04 IST
22    23:04 IST
23    23:04 IST
24    23:04 IST
25    23:04 IST
26    23:04 IST
27    23:04 IST
28    23:04 IST
29    23:04 IST
30    23:04 IST
Name: Time, dtype: str

## Accessing maximum columns

In [12]:
# Accessing multiple column
print(df[["Time", "Location"]])

         Time                       Location
0   23:04 IST  Bharsul, India 10-day Weather
1   23:04 IST  Bharsul, India 10-day Weather
2   23:04 IST  Bharsul, India 10-day Weather
3   23:04 IST  Bharsul, India 10-day Weather
4   23:04 IST  Bharsul, India 10-day Weather
5   23:04 IST  Bharsul, India 10-day Weather
6   23:04 IST  Bharsul, India 10-day Weather
7   23:04 IST  Bharsul, India 10-day Weather
8   23:04 IST  Bharsul, India 10-day Weather
9   23:04 IST  Bharsul, India 10-day Weather
10  23:04 IST  Bharsul, India 10-day Weather
11  23:04 IST  Bharsul, India 10-day Weather
12  23:04 IST  Bharsul, India 10-day Weather
13  23:04 IST  Bharsul, India 10-day Weather
14  23:04 IST  Bharsul, India 10-day Weather
15       Time                       Location
16  23:04 IST  Bharsul, India 10-day Weather
17  23:04 IST  Bharsul, India 10-day Weather
18  23:04 IST  Bharsul, India 10-day Weather
19  23:04 IST  Bharsul, India 10-day Weather
20  23:04 IST  Bharsul, India 10-day Weather
21  23:04 IST  Bharsul, India 10-day Weather
22  23:04 IST  Bharsul, India 10-day Weather
23  23:04 IST  Bharsul, India 10-day Weather
24  23:04 IST  Bharsul, India 10-day Weather
25  23:04 IST  Bharsul, India 10-day Weather
26  23:04 IST  Bharsul, India 10-day Weather
27  23:04 IST  Bharsul, India 10-day Weather
28  23:04 IST  Bharsul, India 10-day Weather
29  23:04 IST  Bharsul, India 10-day Weather
30  23:04 IST  Bharsul, India 10-day Weather

## Accessing rows

In [13]:
# Iloc()
print(df.iloc[10])

MIN temp (deg Celcius)                                                   19
Location                                      Bharsul, India 10-day Weather
Time                                                              23:04 IST
Wind                                                             NE 7 km/h
MAX temp (deg Celcius)                                                   33
Description                                                           Sunny
Precipitation (in %)                                                      0
Date                                                                 28 OCT
Other Details             Generally clear. High 33ºC. Winds NE and varia...
Humidity (in %)                                                          28
Day                                                                     Sun
Name: 10, dtype: str

In [14]:
print(df.loc[0])  # First row by index

MIN temp (deg Celcius)                                                   22
Location                                      Bharsul, India 10-day Weather
Time                                                              23:04 IST
Wind                                                             NE 2 km/h
MAX temp (deg Celcius)                                                   --
Description                                                           Clear
Precipitation (in %)                                                      0
Date                                                                 18 OCT
Other Details             Generally clear. Low 22ºC. Winds NE and variable.
Humidity (in %)                                                          48
Day                                                                 Tonight
Name: 0, dtype: str

## Row slicing

In [15]:
# slicing Rows
print(df.iloc[0:1])

  MIN temp (deg Celcius)                       Location       Time  \
0                     22  Bharsul, India 10-day Weather  23:04 IST

         Wind MAX temp (deg Celcius) Description Precipitation (in %)    Date  \
0  NE 2 km/h                      --       Clear                    0  18 OCT

                                       Other Details Humidity (in %)      Day
0  Generally clear. Low 22ºC. Winds NE and variable.              48  Tonight

## check for duplicates

In [16]:
# check for duplicates 
df.duplicated

<bound method DataFrame.duplicated of     MIN temp (deg Celcius)                       Location       Time  \
0                       22  Bharsul, India 10-day Weather  23:04 IST
1                       22  Bharsul, India 10-day Weather  23:04 IST
2                       22  Bharsul, India 10-day Weather  23:04 IST
3                       21  Bharsul, India 10-day Weather  23:04 IST
4                       21  Bharsul, India 10-day Weather  23:04 IST
5                       21  Bharsul, India 10-day Weather  23:04 IST
6                       21  Bharsul, India 10-day Weather  23:04 IST
7                       20  Bharsul, India 10-day Weather  23:04 IST
8                       20  Bharsul, India 10-day Weather  23:04 IST
9                       19  Bharsul, India 10-day Weather  23:04 IST
10                      19  Bharsul, India 10-day Weather  23:04 IST
11                      19  Bharsul, India 10-day Weather  23:04 IST
12                      19  Bharsul, India 10-day Weather  23:04 IST
13                      19  Bharsul, India 10-day Weather  23:04 IST
14                      19  Bharsul, India 10-day Weather  23:04 IST
15  MIN temp (deg Celcius)                       Location       Time
16                      22  Bharsul, India 10-day Weather  23:04 IST
17                      22  Bharsul, India 10-day Weather  23:04 IST
18                      22  Bharsul, India 10-day Weather  23:04 IST
19                      21  Bharsul, India 10-day Weather  23:04 IST
20                      21  Bharsul, India 10-day Weather  23:04 IST
21                      21  Bharsul, India 10-day Weather  23:04 IST
22                      21  Bharsul, India 10-day Weather  23:04 IST
23                      20  Bharsul, India 10-day Weather  23:04 IST
24                      20  Bharsul, India 10-day Weather  23:04 IST
25                      19  Bharsul, India 10-day Weather  23:04 IST
26                      19  Bharsul, India 10-day Weather  23:04 IST
27                      19  Bharsul, India 10-day Weather  23:04 IST
28                      19  Bharsul, India 10-day Weather  23:04 IST
29                      19  Bharsul, India 10-day Weather  23:04 IST
30                      19  Bharsul, India 10-day Weather  23:04 IST

           Wind  MAX temp (deg Celcius)   Description  Precipitation (in %)  \
0    NE 2 km/h                       --         Clear                     0
1   NNW 7 km/h                       36  Mostly Sunny                     0
2   SSW 5 km/h                       35         Sunny                     0
3   WSW 9 km/h                       36         Sunny                     0
4     N 9 km/h                       35         Sunny                     0
5     W 8 km/h                       35         Sunny                     0
6   SSE 7 km/h                       34  Mostly Sunny                     0
7   SSW 9 km/h                       34  Mostly Sunny                     0
8     E 7 km/h                       34  Mostly Sunny                     0
9   NE 10 km/h                       34         Sunny                     0
10   NE 7 km/h                       33         Sunny                     0
11  ENE 6 km/h                       33         Sunny                     0
12    E 6 km/h                       33         Sunny                     0
13  ESE 5 km/h                       33         Sunny                     0
14  NNW 5 km/h                       33         Sunny                     0
15         Wind  MAX temp (deg Celcius)   Description  Precipitation (in %)
16   NE 2 km/h                       --         Clear                     0
17  NNW 7 km/h                       36  Mostly Sunny                     0
18  SSW 5 km/h                       35         Sunny                     0
19  WSW 9 km/h                       36         Sunny                     0
20    N 9 km/h                       35         Sunny                     0
21    W 8 km/h                       35         Sunny                     0
22  SSE 7 km/h                       34  Mostly Sunny                     0
23  SSW 9 km/h                       34  Mostly Sunny                     0
24    E 7 km/h                       34  Mostly Sunny                     0
25  NE 10 km/h                       34         Sunny                     0
26   NE 7 km/h                       33         Sunny                     0
27  ENE 6 km/h                       33         Sunny                     0
28    E 6 km/h                       33         Sunny                     0
29  ESE 5 km/h                       33         Sunny                     0
30  NNW 5 km/h                       33         Sunny                     0

      Date                                      Other Details  \
0   18 OCT  Generally clear. Low 22ºC. Winds NE and variable.
1   19 OCT  Generally clear. High 36ºC. Winds NNW and vari...
2   20 OCT  Generally clear. High 35ºC. Winds SSW and vari...
3   21 OCT  Generally clear. High 36ºC. Winds WSW and vari...
4   22 OCT  Generally clear. High 35ºC. Winds N and variable.
5   23 OCT  Generally clear. High 35ºC. Winds W and variable.
6   24 OCT  Generally clear. High 34ºC. Winds SSE and vari...
7   25 OCT  Generally clear. High 34ºC. Winds SSW and vari...
8   26 OCT  Generally clear. High 34ºC. Winds E and variable.
9   27 OCT  Generally clear. High 34ºC. Winds NE at 10 to ...
10  28 OCT  Generally clear. High 33ºC. Winds NE and varia...
11  29 OCT  Generally clear. High 33ºC. Winds ENE and vari...
12  30 OCT  Generally clear. High 33ºC. Winds E and variable.
13  31 OCT  Generally clear. High 33ºC. Winds ESE and vari...
14   1 NOV  Generally clear. High 33ºC. Winds NNW and vari...
15    Date                                      Other Details
16  18 OCT  Generally clear. Low 22ºC. Winds NE and variable.
17  19 OCT  Generally clear. High 36ºC. Winds NNW and vari...
18  20 OCT  Generally clear. High 35ºC. Winds SSW and vari...
19  21 OCT  Generally clear. High 36ºC. Winds WSW and vari...
20  22 OCT  Generally clear. High 35ºC. Winds N and variable.
21  23 OCT  Generally clear. High 35ºC. Winds W and variable.
22  24 OCT  Generally clear. High 34ºC. Winds SSE and vari...
23  25 OCT  Generally clear. High 34ºC. Winds SSW and vari...
24  26 OCT  Generally clear. High 34ºC. Winds E and variable.
25  27 OCT  Generally clear. High 34ºC. Winds NE at 10 to ...
26  28 OCT  Generally clear. High 33ºC. Winds NE and varia...
27  29 OCT  Generally clear. High 33ºC. Winds ENE and vari...
28  30 OCT  Generally clear. High 33ºC. Winds E and variable.
29  31 OCT  Generally clear. High 33ºC. Winds ESE and vari...
30   1 NOV  Generally clear. High 33ºC. Winds NNW and vari...

    Humidity (in %)      Day
0                48  Tonight
1                29      Fri
2                29      Sat
3                32      Sun
4                31      Mon
5                29      Tue
6                28      Wed
7                27      Thu
8                29      Fri
9                30      Sat
10               28      Sun
11               26      Mon
12               27      Tue
13               27      Wed
14               28      Thu
15  Humidity (in %)      Day
16               48  Tonight
17               29      Fri
18               29      Sat
19               32      Sun
20               31      Mon
21               29      Tue
22               28      Wed
23               27      Thu
24               29      Fri
25               30      Sat
26               28      Sun
27               26      Mon
28               27      Tue
29               27      Wed
30               28      Thu  >

## Removing Duplicates

In [17]:
df.dropna()

,MIN temp (deg Celcius),Location,Time,Wind,MAX temp (deg Celcius),Description,Precipitation (in %),Date,Other Details,Humidity (in %),Day
0,22,"Bharsul, India 10-day Weather",23:04 IST,NE 2 km/h,--,Clear,0,18 OCT,Generally clear. Low 22ºC. Winds NE and variable.,48,Tonight
1,22,"Bharsul, India 10-day Weather",23:04 IST,NNW 7 km/h,36,Mostly Sunny,0,19 OCT,Generally clear. High 36ºC. Winds NNW and vari...,29,Fri
2,22,"Bharsul, India 10-day Weather",23:04 IST,SSW 5 km/h,35,Sunny,0,20 OCT,Generally clear. High 35ºC. Winds SSW and vari...,29,Sat
3,21,"Bharsul, India 10-day Weather",23:04 IST,WSW 9 km/h,36,Sunny,0,21 OCT,Generally clear. High 36ºC. Winds WSW and vari...,32,Sun
4,21,"Bharsul, India 10-day Weather",23:04 IST,N 9 km/h,35,Sunny,0,22 OCT,Generally clear. High 35ºC. Winds N and variable.,31,Mon
5,21,"Bharsul, India 10-day Weather",23:04 IST,W 8 km/h,35,Sunny,0,23 OCT,Generally clear. High 35ºC. Winds W and variable.,29,Tue
6,21,"Bharsul, India 10-day Weather",23:04 IST,SSE 7 km/h,34,Mostly Sunny,0,24 OCT,Generally clear. High 34ºC. Winds SSE and vari...,28,Wed
7,20,"Bharsul, India 10-day Weather",23:04 IST,SSW 9 km/h,34,Mostly Sunny,0,25 OCT,Generally clear. High 34ºC. Winds SSW and vari...,27,Thu
8,20,"Bharsul, India 10-day Weather",23:04 IST,E 7 km/h,34,Mostly Sunny,0,26 OCT,Generally clear. High 34ºC. Winds E and variable.,29,Fri
9,19,"Bharsul, India 10-day Weather",23:04 IST,NE 10 km/h,34,Sunny,0,27 OCT,Generally clear. High 34ºC. Winds NE at 10 to ...,30,Sat
10,19,"Bharsul, India 10-day Weather",23:04 IST,NE 7 km/h,33,Sunny,0,28 OCT,Generally clear. High 33ºC. Winds NE and varia...,28,Sun
11,19,"Bharsul, India 10-day Weather",23:04 IST,ENE 6 km/h,33,Sunny,0,29 OCT,Generally clear. High 33ºC. Winds ENE and vari...,26,Mon
12,19,"Bharsul, India 10-day Weather",23:04 IST,E 6 km/h,33,Sunny,0,30 OCT,Generally clear. High 33ºC. Winds E and variable.,27,Tue
13,19,"Bharsul, India 10-day Weather",23:04 IST,ESE 5 km/h,33,Sunny,0,31 OCT,Generally clear. High 33ºC. Winds ESE and vari...,27,Wed
14,19,"Bharsul, India 10-day Weather",23:04 IST,NNW 5 km/h,33,Sunny,0,1 NOV,Generally clear. High 33ºC. Winds NNW and vari...,28,Thu
15,MIN temp (deg Celcius),Location,Time,Wind,MAX temp (deg Celcius),Description,Precipitation (in %),Date,Other Details,Humidity (in %),Day
16,22,"Bharsul, India 10-day Weather",23:04 IST,NE 2 km/h,--,Clear,0,18 OCT,Generally clear. Low 22ºC. Winds NE and variable.,48,Tonight
17,22,"Bharsul, India 10-day Weather",23:04 IST,NNW 7 km/h,36,Mostly Sunny,0,19 OCT,Generally clear. High 36ºC. Winds NNW and vari...,29,Fri
18,22,"Bharsul, India 10-day Weather",23:04 IST,SSW 5 km/h,35,Sunny,0,20 OCT,Generally clear. High 35ºC. Winds SSW and vari...,29,Sat
19,21,"Bharsul, India 10-day Weather",23:04 IST,WSW 9 km/h,36,Sunny,0,21 OCT,Generally clear. High 36ºC. Winds WSW and vari...,32,Sun
20,21,"Bharsul, India 10-day Weather",23:04 IST,N 9 km/h,35,Sunny,0,22 OCT,Generally clear. High 35ºC. Winds N and variable.,31,Mon
21,21,"Bharsul, India 10-day Weather",23:04 IST,W 8 km/h,35,Sunny,0,23 OCT,Generally clear. High 35ºC. Winds W and variable.,29,Tue
22,21,"Bharsul, India 10-day Weather",23:04 IST,SSE 7 km/h,34,Mostly Sunny,0,24 OCT,Generally clear. High 34ºC. Winds SSE and vari...,28,Wed
23,20,"Bharsul, India 10-day Weather",23:04 IST,SSW 9 km/h,34,Mostly Sunny,0,25 OCT,Generally clear. High 34ºC. Winds SSW and vari...,27,Thu
24,20,"Bharsul, India 10-day Weather",23:04 IST,E 7 km/h,34,Mostly Sunny,0,26 OCT,Generally clear. High 34ºC. Winds E and variable.,29,Fri
25,19,"Bharsul, India 10-day Weather",23:04 IST,NE 10 km/h,34,Sunny,0,27 OCT,Generally clear. High 34ºC. Winds NE at 10 to ...,30,Sat
26,19,"Bharsul, India 10-day Weather",23:04 IST,NE 7 km/h,33,Sunny,0,28 OCT,Generally clear. High 33ºC. Winds NE and varia...,28,Sun
27,19,"Bharsul, India 10-day Weather",23:04 IST,ENE 6 km/h,33,Sunny,0,29 OCT,Generally clear. High 33ºC. Winds ENE and vari...,26,Mon
28,19,"Bharsul, India 10-day Weather",23:04 IST,E 6 km/h,33,Sunny,0,30 OCT,Generally clear. High 33ºC. Winds E and variable.,27,Tue
29,19,"Bharsul, India 10-day Weather",23:04 IST,ESE 5 km/h,33,Sunny,0,31 OCT,Generally clear. High 33ºC. Winds ESE and vari...,27,Wed
30,19,"Bharsul, India 10-day Weather",23:04 IST,NNW 5 km/h,33,Sunny,0,1 NOV,Generally clear. High 33ºC. Winds NNW and vari...,28,Thu

## check for unique values

In [18]:
print(df['Time'].unique())

<StringArray>
['23:04 IST', 'Time']
Length: 2, dtype: str

## nunique

In [19]:
print(df['Location'].nunique())

2

# values count

In [20]:

print(df['Wind'].value_counts())

Wind
NE 2 km/h      2
NNW 7 km/h     2
SSW 5 km/h     2
WSW 9 km/h     2
N 9 km/h       2
W 8 km/h       2
SSE 7 km/h     2
SSW 9 km/h     2
E 7 km/h       2
NE 10 km/h     2
NE 7 km/h      2
ENE 6 km/h     2
E 6 km/h       2
ESE 5 km/h     2
NNW 5 km/h     2
Wind           1
Name: count, dtype: int64

# Head()/ Tail

In [21]:
print(df.head(3))

  MIN temp (deg Celcius)                       Location       Time  \
0                     22  Bharsul, India 10-day Weather  23:04 IST
1                     22  Bharsul, India 10-day Weather  23:04 IST
2                     22  Bharsul, India 10-day Weather  23:04 IST

          Wind MAX temp (deg Celcius)   Description Precipitation (in %)  \
0   NE 2 km/h                      --         Clear                    0
1  NNW 7 km/h                      36  Mostly Sunny                    0
2  SSW 5 km/h                      35         Sunny                    0

     Date                                      Other Details Humidity (in %)  \
0  18 OCT  Generally clear. Low 22ºC. Winds NE and variable.              48
1  19 OCT  Generally clear. High 36ºC. Winds NNW and vari...              29
2  20 OCT  Generally clear. High 35ºC. Winds SSW and vari...              29

       Day
0  Tonight
1      Fri
2      Sat

In [22]:
print(df.tail())

   MIN temp (deg Celcius)                       Location       Time  \
26                     19  Bharsul, India 10-day Weather  23:04 IST
27                     19  Bharsul, India 10-day Weather  23:04 IST
28                     19  Bharsul, India 10-day Weather  23:04 IST
29                     19  Bharsul, India 10-day Weather  23:04 IST
30                     19  Bharsul, India 10-day Weather  23:04 IST

           Wind MAX temp (deg Celcius) Description Precipitation (in %)  \
26   NE 7 km/h                      33       Sunny                    0
27  ENE 6 km/h                      33       Sunny                    0
28    E 6 km/h                      33       Sunny                    0
29  ESE 5 km/h                      33       Sunny                    0
30  NNW 5 km/h                      33       Sunny                    0

      Date                                      Other Details Humidity (in %)  \
26  28 OCT  Generally clear. High 33ºC. Winds NE and varia...              28
27  29 OCT  Generally clear. High 33ºC. Winds ENE and vari...              26
28  30 OCT  Generally clear. High 33ºC. Winds E and variable.              27
29  31 OCT  Generally clear. High 33ºC. Winds ESE and vari...              27
30   1 NOV  Generally clear. High 33ºC. Winds NNW and vari...              28

    Day
26  Sun
27  Mon
28  Tue
29  Wed
30  Thu

## checking null values

In [23]:
print(df. isnull(). sum()) # convert indexes to normal python list

MIN temp (deg Celcius)    0
Location                  0
Time                      0
Wind                      0
MAX temp (deg Celcius)    0
Description               0
Precipitation (in %)      0
Date                      0
Other Details             0
Humidity (in %)           0
Day                       0
dtype: int64

In [24]:
df_drop_any = df.dropna()
df_drop_any

,MIN temp (deg Celcius),Location,Time,Wind,MAX temp (deg Celcius),Description,Precipitation (in %),Date,Other Details,Humidity (in %),Day
0,22,"Bharsul, India 10-day Weather",23:04 IST,NE 2 km/h,--,Clear,0,18 OCT,Generally clear. Low 22ºC. Winds NE and variable.,48,Tonight
1,22,"Bharsul, India 10-day Weather",23:04 IST,NNW 7 km/h,36,Mostly Sunny,0,19 OCT,Generally clear. High 36ºC. Winds NNW and vari...,29,Fri
2,22,"Bharsul, India 10-day Weather",23:04 IST,SSW 5 km/h,35,Sunny,0,20 OCT,Generally clear. High 35ºC. Winds SSW and vari...,29,Sat
3,21,"Bharsul, India 10-day Weather",23:04 IST,WSW 9 km/h,36,Sunny,0,21 OCT,Generally clear. High 36ºC. Winds WSW and vari...,32,Sun
4,21,"Bharsul, India 10-day Weather",23:04 IST,N 9 km/h,35,Sunny,0,22 OCT,Generally clear. High 35ºC. Winds N and variable.,31,Mon
5,21,"Bharsul, India 10-day Weather",23:04 IST,W 8 km/h,35,Sunny,0,23 OCT,Generally clear. High 35ºC. Winds W and variable.,29,Tue
6,21,"Bharsul, India 10-day Weather",23:04 IST,SSE 7 km/h,34,Mostly Sunny,0,24 OCT,Generally clear. High 34ºC. Winds SSE and vari...,28,Wed
7,20,"Bharsul, India 10-day Weather",23:04 IST,SSW 9 km/h,34,Mostly Sunny,0,25 OCT,Generally clear. High 34ºC. Winds SSW and vari...,27,Thu
8,20,"Bharsul, India 10-day Weather",23:04 IST,E 7 km/h,34,Mostly Sunny,0,26 OCT,Generally clear. High 34ºC. Winds E and variable.,29,Fri
9,19,"Bharsul, India 10-day Weather",23:04 IST,NE 10 km/h,34,Sunny,0,27 OCT,Generally clear. High 34ºC. Winds NE at 10 to ...,30,Sat
10,19,"Bharsul, India 10-day Weather",23:04 IST,NE 7 km/h,33,Sunny,0,28 OCT,Generally clear. High 33ºC. Winds NE and varia...,28,Sun
11,19,"Bharsul, India 10-day Weather",23:04 IST,ENE 6 km/h,33,Sunny,0,29 OCT,Generally clear. High 33ºC. Winds ENE and vari...,26,Mon
12,19,"Bharsul, India 10-day Weather",23:04 IST,E 6 km/h,33,Sunny,0,30 OCT,Generally clear. High 33ºC. Winds E and variable.,27,Tue
13,19,"Bharsul, India 10-day Weather",23:04 IST,ESE 5 km/h,33,Sunny,0,31 OCT,Generally clear. High 33ºC. Winds ESE and vari...,27,Wed
14,19,"Bharsul, India 10-day Weather",23:04 IST,NNW 5 km/h,33,Sunny,0,1 NOV,Generally clear. High 33ºC. Winds NNW and vari...,28,Thu
15,MIN temp (deg Celcius),Location,Time,Wind,MAX temp (deg Celcius),Description,Precipitation (in %),Date,Other Details,Humidity (in %),Day
16,22,"Bharsul, India 10-day Weather",23:04 IST,NE 2 km/h,--,Clear,0,18 OCT,Generally clear. Low 22ºC. Winds NE and variable.,48,Tonight
17,22,"Bharsul, India 10-day Weather",23:04 IST,NNW 7 km/h,36,Mostly Sunny,0,19 OCT,Generally clear. High 36ºC. Winds NNW and vari...,29,Fri
18,22,"Bharsul, India 10-day Weather",23:04 IST,SSW 5 km/h,35,Sunny,0,20 OCT,Generally clear. High 35ºC. Winds SSW and vari...,29,Sat
19,21,"Bharsul, India 10-day Weather",23:04 IST,WSW 9 km/h,36,Sunny,0,21 OCT,Generally clear. High 36ºC. Winds WSW and vari...,32,Sun
20,21,"Bharsul, India 10-day Weather",23:04 IST,N 9 km/h,35,Sunny,0,22 OCT,Generally clear. High 35ºC. Winds N and variable.,31,Mon
21,21,"Bharsul, India 10-day Weather",23:04 IST,W 8 km/h,35,Sunny,0,23 OCT,Generally clear. High 35ºC. Winds W and variable.,29,Tue
22,21,"Bharsul, India 10-day Weather",23:04 IST,SSE 7 km/h,34,Mostly Sunny,0,24 OCT,Generally clear. High 34ºC. Winds SSE and vari...,28,Wed
23,20,"Bharsul, India 10-day Weather",23:04 IST,SSW 9 km/h,34,Mostly Sunny,0,25 OCT,Generally clear. High 34ºC. Winds SSW and vari...,27,Thu
24,20,"Bharsul, India 10-day Weather",23:04 IST,E 7 km/h,34,Mostly Sunny,0,26 OCT,Generally clear. High 34ºC. Winds E and variable.,29,Fri
25,19,"Bharsul, India 10-day Weather",23:04 IST,NE 10 km/h,34,Sunny,0,27 OCT,Generally clear. High 34ºC. Winds NE at 10 to ...,30,Sat
26,19,"Bharsul, India 10-day Weather",23:04 IST,NE 7 km/h,33,Sunny,0,28 OCT,Generally clear. High 33ºC. Winds NE and varia...,28,Sun
27,19,"Bharsul, India 10-day Weather",23:04 IST,ENE 6 km/h,33,Sunny,0,29 OCT,Generally clear. High 33ºC. Winds ENE and vari...,26,Mon
28,19,"Bharsul, India 10-day Weather",23:04 IST,E 6 km/h,33,Sunny,0,30 OCT,Generally clear. High 33ºC. Winds E and variable.,27,Tue
29,19,"Bharsul, India 10-day Weather",23:04 IST,ESE 5 km/h,33,Sunny,0,31 OCT,Generally clear. High 33ºC. Winds ESE and vari...,27,Wed
30,19,"Bharsul, India 10-day Weather",23:04 IST,NNW 5 km/h,33,Sunny,0,1 NOV,Generally clear. High 33ºC. Winds NNW and vari...,28,Thu